enabled: true
production-mode: false
sidebar: true
google_fonts_local: true
type_logo_header: both
slogan: null
menu_langswitcher: false
menu_search: true
menu_login: true
blog_page: /blog
miniposts: true
miniposts_category: minipost
miniposts_number: 3
recent_posts_enabled: false
recent_posts_number: 5
footer:
  title: null
  description: null
  copyright_text: null
  button_text: null
  button_url: null
enable_social: true
social_style: brands
custommenus:
  enabled: true
custom_logo:
  user/themes/future-sh-2024/images/logo/wappen.gif:
    name: wappen.gif
    full_path: wappen.gif
    type: image/gif
    size: 19445
    path: user/themes/future-sh-2024/images/logo/wappen.gif
custom_logo_mobile: {  }
