enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/schimmelhaeuer.jpeg:
    name: schimmelhaeuer.jpeg
    full_path: schimmelhaeuer.jpeg
    type: image/jpeg
    size: 929258
    path: user/themes/quark/images/logo/schimmelhaeuer.jpeg
custom_logo_mobile: {  }
