enabled: true
production-mode: false
sidebar: true
google_fonts_local: true
type_logo_header: both
slogan: null
menu_langswitcher: false
menu_search: true
menu_login: true
blog_page: /news
miniposts: false
miniposts_category: minipost
miniposts_number: 3
recent_posts_enabled: true
recent_posts_number: 3
footer:
  title: ' '
  description: null
  copyright_text: null
  button_text: Impressum
  button_url: /impressum
enable_social: true
social_style: brands
custommenus:
  enabled: true
custom_logo:
  user/themes/future-sh-2024/images/logo/wappen.png:
    name: wappen.png
    full_path: wappen.png
    type: image/png
    size: 569487
    path: user/themes/future-sh-2024/images/logo/wappen.png
custom_logo_mobile: {  }
favicon:
  user/themes/future-sh-2024/images/favicon.ico:
    name: favicon.ico
    full_path: favicon.ico
    type: image/vnd.microsoft.icon
    size: 15086
    path: user/themes/future-sh-2024/images/favicon.ico
